# Generated by Django 3.0.2 on 2020-01-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sale_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='url_for_sale',
            field=models.URLField(blank=True, null=True),
        ),
    ]
