# Generated by Django 3.0.2 on 2020-01-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200105_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='from_exct_until',
            field=models.CharField(blank=True, choices=[('>=', 'От'), ('==', 'Ровно'), ('<=', 'До')], max_length=2, null=True),
        ),
    ]
