# Generated by Django 3.0.2 on 2020-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sale_from_exct_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='type_of_currency',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='type_of_sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_measure',
            field=models.CharField(blank=True, choices=[('%%', 'Процент'), ('RR', 'Российский рубль'), ('USD', 'American dollar'), ('EUR', 'Euro')], max_length=3, null=True),
        ),
    ]
