# Generated by Django 3.0.2 on 2020-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200105_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
