# Generated by Django 3.0.2 on 2020-01-05 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sale_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='valid_until',
            field=models.DateTimeField(default=datetime.date(2020, 1, 1), verbose_name='Действителен до'),
        ),
    ]
