# Generated by Django 3.0.2 on 2020-01-07 13:51

from django.db import migrations, models
import shop.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sale_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to=shop.utilities.get_timestamp_path, verbose_name='Логотип магазина'),
        ),
    ]
